version: '3.4'

services:
  backend:
    build: ./MultiFactorAuthentication/MultiFactorAuthentication.Web
    ports:
      - "5555:80"     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 